# Generated by Django 2.1.1 on 2019-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='end_term',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='mid_term',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='practical',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
